print("Calculadora simple")
print("Necesito dos números")
a = int(input("Dame el primer número "))
b = int(input("Dame el segundo número "))
print("Suma:", a + b)
print("Resta:", a - b)
print("Producto:", a * b)
print("División:", a / b)
print("Potencia:", a ** b)
print("Cociente:", a // b)
print("Residuo:", a % b)
